namespace Clio.RemoteServices.GitHub.Dto;

public record User(
	string login,
	int id,
	string node_id,
	string avatar_url,
	string gravatar_id,
	string url,
	string html_url,
	string followers_url,
	string following_url,
	string gists_url,
	string starred_url,
	string subscriptions_url,
	string organizations_url,
	string repos_url,
	string events_url,
	string received_events_url,
	string type,
	bool site_admin,
	string name,
	string company,
	string blog,
	string location,
	string email,
	bool hireable,
	string bio,
	object twitter_username,
	int public_repos,
	int public_gists,
	int followers,
	int following,
	string created_at,
	string updated_at,
	Plan plan
);